import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk, Gdk
import datetime
from . import config
from .config import dbglog


class ClassNotebook(Gtk.Notebook):
    """ This is one of the tree views, which are displayed by the mainwindow.
    The notebook has a tab for each class. The tabs are generated by calling update()
    from the .timetable.
    """
    def __init__(self, parent):
        Gtk.Notebook.__init__(self)
        self.parent = parent

        # here come all current tabs
        self.__tabs = []
        self.connect("map", self.showHandler)
        self.set_scrollable( True )
        self.__savelist = []
        self.currentPage = None
        #self.update_tabs()
        #print("nb created")

    def showHandler(self, wid):
        """When the notebook becomes visible, update all tabs."""
        self.update()

    def update_tabs(self):
        """Refreshes the tabs and updates the sequences."""
        # first, remove all
        for tab in self.__tabs:
            self.detach_tab(tab)

        self.__tabs = []

        # now add from the time table
        for name in self.parent.environment.timeTab.getClassList():
            #page = Gtk.Box()
            #page.add(SequenceWindow())
            page = SequenceTV(name, parent=self)
            self.append_page(page, Gtk.Label( name ))
            self.__tabs.append(page)
            page.update()

    def update(self):
        self.update_tabs()


    def switch_to_tab(self, class_name):
        """show tab with the given class"""
        i = 0
        for name in self.parent.environment.timeTab.getClassList():
            if name == class_name:
                self.set_current_page(i)
                self.__tabs[i].update()
                break
            i = i + 1

    def get_tab(self, class_name):
        """return the tab for the given classname"""
        i = 0
        for name in self.parent.environment.timeTab.getClassList():
            if name == class_name:
                return self.__tabs[i]
            i = i + 1


class SequenceTV(Gtk.ScrolledWindow):
    """A Textview consisiting of the

        number of lesson
        date of lesson
        period of lesson and
        topic of the lesson.

    The content is read from the timetable and written into the timetable, when a
    tab is switched or the view (parent) becomes invisible.
    """

    def __init__(self, name, parent):
        # testing

        Gtk.ScrolledWindow.__init__(self )
        self.parent = parent

        self.name = name    # classname

        # a scrollbar for the child widget (that is going to be the textview)
        #scrolled_window = Gtk.ScrolledWindow()
        self.set_margin_top(5)
        self.set_margin_bottom(5)
        self.set_margin_start(5)
        self.set_margin_end(5)
        self.set_policy(Gtk.PolicyType.AUTOMATIC, Gtk.PolicyType.AUTOMATIC)

        self.sequenceBuf = Gtk.TextBuffer()
        self.nrBuf = Gtk.TextBuffer()
        self.dateBuf = Gtk.TextBuffer()
        self.periodBuf = Gtk.TextBuffer()

        nrLab = Gtk.Label()
        dateLab = Gtk.Label()
        periodLab = Gtk.Label()
        sequenceLab = Gtk.Label()

        vsep1 = Gtk.Separator(orientation=Gtk.Orientation.VERTICAL)
        vsep2 = Gtk.Separator(orientation=Gtk.Orientation.VERTICAL)
        vsep3 = Gtk.Separator(orientation=Gtk.Orientation.VERTICAL)

        nrLab.set_text(_("#"))
        dateLab.set_text(_("date"))
        periodLab.set_text(_("h"))
